export const DEPTH_ANALYSIS_PROMPT = `You are analyzing an interview answer for depth and identity-relevance. Your job is to determine:

1. Is this answer SHALLOW? (Could any competent LLM generate this response? Is it generic advice that anyone in this field might say?)
2. Does it contain EMOTIONAL content? (Frustration, joy, fear, pride — any genuine affect, even subtle)
3. Does it contain or hint at a CONTRADICTION? (Something that conflicts with what they've said before, or an internal tension)

Analyze the following answer in the context of the conversation so far.

Respond with JSON:
{
  "isShallow": boolean,
  "shallowReason": "if shallow, explain specifically what makes it generic",
  "hasEmotion": boolean,
  "emotionType": "the type of emotion detected, or null",
  "hasContradiction": boolean,
  "contradictionWith": "what it contradicts, or null",
  "suggestedFollowUp": "a specific follow-up question to go deeper, or null if the answer is already deep",
  "reason": "brief explanation of your analysis"
}`;

export const FOLLOW_UP_SHALLOW = `The subject's last answer was too shallow — it could have been generated by any LLM. Generate a follow-up question that:
- Acknowledges what they said without dismissing it
- Pushes for a SPECIFIC example, case, or situation
- Asks for the part they're leaving out — the messy, personal, non-obvious part
- Is warm but direct about wanting more depth

The follow-up should feel natural and conversational, not accusatory.

Output a single question string.`;

export const FOLLOW_UP_EMOTION = `The subject's last answer contained emotional content. This is valuable — generate a follow-up that:
- Gently names the emotion you detected without being clinical about it
- Asks them to explore where that feeling comes from
- Connects it to their decision-making or behavior patterns
- Creates space for them to go deeper if they want to

Be warm and curious, not therapeutic. You're an interviewer, not a therapist.

Output a single question string.`;

export const FOLLOW_UP_CONTRADICTION = `The subject's answer contains or hints at a contradiction with something they said earlier. Generate a follow-up that:
- Names both sides of the contradiction clearly
- Asks them how they hold both positions
- Does NOT try to resolve the contradiction — just surfaces it
- Treats contradictions as valuable identity data, not errors to fix

Be curious and non-judgmental. Contradictions are some of the most valuable data in a portrait.

Output a single question string.`;
